// Code generated by golang-gen-getter. DO NOT EDIT.
package e2e_test

import "github.com/youta1119/golang-gen-getter/e2e_test/other"

func (s *Structure) ID() string {
	return s.id
}
func (s *Structure) ExternalStruct() *other.Other {
	return s.externalStruct
}
func (s *Structure) ChildStruct() ChildStructure {
	return s.childStruct
}
func (s *Structure) ChildStructSlice() []*ChildStructure {
	return s.childStructSlice
}
